### ISSUE TITLE
Add new scoreboard for metadata

### ISSUE THREAD

**Issue by theogiraudet** [Gunivers/Bookshelf#44]
Sometimes, getting information about the library in game can be really convenient. I propose to add a new scoreboard `bs.metadata`. This scoreboard will store information about the library itself. For instance, each installed module will create a new score in this scoreboard where the key is the module name and the value `1`. This allows to other modules/systems to detect if right dependencies are available. This scoreboard can also store Bookshelf version if we version the library one day.

**Comment by ascpial** [comment]
- I think it's strange to need this type of metadata.

The user is not supposed to install the lib, so there should be no need for the author of a map or datapack.

Maybe it might be helpfull to detect conflicts with other datapacks but I'm not sure about that.

**Comment by theogiraudet** [comment]
Let's suppose we install an "external module" that depend of the lib but that is not part of it. If this system need specific modules, it can detect through this scoreboard if these modules are installed. It's also a good way to detect if Bookshelf is installed on the current map. It's more for the development phase than for the production phase.

**Comment by ascpial** [comment]
Also, if you have a lot of projects, it could be usefull to quickly get the version of the lib for a project.

**Comment by Leirof** [comment]
> I think it's strange to need this type of metadata.
> 
> The user is not supposed to install the lib, so there should be no need for the author of a map or datapack.
> 
> Maybe it might be helpfull to detect conflicts with other datapacks but I'm not sure about that.

In the context of this project, the user is the author of the map
But as every metadata, it doesn't intend to be used by the user but by the product itself or product that interact with it

Currently there is a `bs.activeModule` score (still undocumented because it is new) so I will refactor it in `bs.metadata` and create a fakeplayer "version" that I will increment at each version (it will a kind of ID of the version, but not related to the version name for which the format can be subject to change). Sounds good?

**Comment by aksiome** [comment]
Using the storage to store metadata seems a bit more appropriate since we can store an arbitrary amount of data with any format. Will follow this in #149 !
